version: '3.9'
services:
  ui:
    user: node
    image: node:lts-alpine
    container_name: ui
    build: ./ui
    volumes:
      - ./ui:/app
    command: npm run dev  --prefix ./app -- --host
    ports:
      - 4000:4000
  api:
    user: node
    image: node:lts-alpine
    container_name: api
    build: ./api
    environment:
      - PORT=4001
    volumes:
      - ./api:/app
    command: npm run dev --prefix ./app
    ports:
      - "4001:4001"
  db:
    image: postgres:14-alpine
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    volumes:
      - db_data:/var/lib/postgresql/data/:delegated
    ports:
    - 5432:5432

volumes:
  db_data: